### ISSUE TITLE
Move babelquarto modified function into separate repo

### ISSUE THREAD

**Issue by PBBlomquist** [appliedepi/case_studies#33]

**Comment by PBBlomquist** [comment]
From Alex: We are going to start a translation repo that pulls some of his different scripts out of hidden places and puts them in functions, so that we have that documented and tested properly. As well as functions for translating datasets. And a packagedown website that will have walkthroughs for people doing translations on epirhandbook, case studies and courses. 
Functions luong will pull together: 
1) wrapper around babelquarto: this is a three stap function that first adds a ghost qmd file for case studies that dont yet exist in other languages, second runs babelquarto, third deletes resulting ghost html files for the non-existant languages. (currently he has this sat in the casestudies repo runfile, but has pulled babelquarto source code, which is not sustainable for versioning and if there are babelquarto updates). 
2) function for course exercises: currently a script that creates an rmd for each module then runs babeldown over the new rmd, then pulls them in to separate appropriately named folders. (This currently sits in the introexercises repo - but could be generalised to be used across advanced courses).

**Comment by aspina7** [comment]
started a new repo for this with some notes and issues. @ntluong95 you should be able to pull request. 
https://github.com/appliedepi/aetranslations
