### ISSUE TITLE
Finish drafting the instructions page

### ISSUE THREAD

**Issue by alanahjansen** [appliedepi/case_studies#36]
>
**Location of file**

You can find the Google Docs file where the initial draft has been started [here](https://docs.google.com/document/d/18hKY-pnYX_fjYe5dPQ7h7mn4thWCMJm9A-hUQa5ryr4/edit?usp=sharing).

**Comment by PBBlomquist** [comment]
Edited further to have general help page at the top, the R specific stuff at the bottom. Moved definition of case study to the home page. 

 a9b5887c2c610a53978162f9a5e919bed898d966

**Comment by alanahjansen** [comment]
Reviewed the How-to Guide and have provided minor edits to Paula. I think that it's good to go!
